"""Enhanced DNS analysis schema

Revision ID: 02d1c1bd024e
Revises: afa2efa2014a
Create Date: 2025-07-15 18:56:45.017216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d1c1bd024e'
down_revision: Union[str, Sequence[str], None] = 'afa2efa2014a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with proper TEXT to JSON conversion."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_checks', sa.Column('grade', sa.String(length=5), nullable=True))
    op.add_column('domain_checks', sa.Column('issues', sa.JSON(), nullable=True))
    
    # Convert TEXT columns to JSON with proper casting
    op.execute('ALTER TABLE domain_checks ALTER COLUMN spf_record TYPE JSON USING spf_record::json')
    op.execute('ALTER TABLE domain_checks ALTER COLUMN dkim_record TYPE JSON USING dkim_record::json')
    op.execute('ALTER TABLE domain_checks ALTER COLUMN dmarc_record TYPE JSON USING dmarc_record::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domain_checks', 'dmarc_record',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('domain_checks', 'dkim_record',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('domain_checks', 'spf_record',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('domain_checks', 'issues')
    op.drop_column('domain_checks', 'grade')
    # ### end Alembic commands ###
