"""add_security_summary_column

Revision ID: 6b897e8e0f54
Revises: 02d1c1bd024e
Create Date: 2025-07-17 11:38:06.405854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b897e8e0f54'
down_revision: Union[str, Sequence[str], None] = '02d1c1bd024e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add security_summary column."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_checks', sa.Column('security_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove security_summary column."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain_checks', 'security_summary')
    # ### end Alembic commands ###
