"""Remove AnonymousUsage table and client_ip column

Revision ID: 836327f86dca
Revises: 4b665506209c
Create Date: 2025-07-18 23:18:01.331626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '836327f86dca'
down_revision: Union[str, Sequence[str], None] = '4b665506209c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_usage_client_ip'), table_name='anonymous_usage')
    op.drop_index(op.f('ix_anonymous_usage_domain'), table_name='anonymous_usage')
    op.drop_index(op.f('ix_anonymous_usage_id'), table_name='anonymous_usage')
    op.drop_index(op.f('ix_anonymous_usage_month_year'), table_name='anonymous_usage')
    op.drop_table('anonymous_usage')
    op.drop_column('domain_checks', 'client_ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_checks', sa.Column('client_ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('anonymous_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_ip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('check_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_check', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('month_year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('anonymous_usage_pkey'))
    )
    op.create_index(op.f('ix_anonymous_usage_month_year'), 'anonymous_usage', ['month_year'], unique=False)
    op.create_index(op.f('ix_anonymous_usage_id'), 'anonymous_usage', ['id'], unique=False)
    op.create_index(op.f('ix_anonymous_usage_domain'), 'anonymous_usage', ['domain'], unique=False)
    op.create_index(op.f('ix_anonymous_usage_client_ip'), 'anonymous_usage', ['client_ip'], unique=False)
    # ### end Alembic commands ###
