"""Initial migration

Revision ID: afa2efa2014a
Revises: 
Create Date: 2025-07-15 18:30:07.070315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa2efa2014a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('mx_record', sa.JSON(), nullable=True),
    sa.Column('spf_record', sa.Text(), nullable=True),
    sa.Column('dkim_record', sa.Text(), nullable=True),
    sa.Column('dmarc_record', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('opt_in_marketing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_checks_domain'), 'domain_checks', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_checks_email'), 'domain_checks', ['email'], unique=False)
    op.create_index(op.f('ix_domain_checks_id'), 'domain_checks', ['id'], unique=False)
    op.create_table('domain_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('check_count', sa.Integer(), nullable=True),
    sa.Column('last_check', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('month_year', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_usage_domain'), 'domain_usage', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_usage_id'), 'domain_usage', ['id'], unique=False)
    op.create_index(op.f('ix_domain_usage_month_year'), 'domain_usage', ['month_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_usage_month_year'), table_name='domain_usage')
    op.drop_index(op.f('ix_domain_usage_id'), table_name='domain_usage')
    op.drop_index(op.f('ix_domain_usage_domain'), table_name='domain_usage')
    op.drop_table('domain_usage')
    op.drop_index(op.f('ix_domain_checks_id'), table_name='domain_checks')
    op.drop_index(op.f('ix_domain_checks_email'), table_name='domain_checks')
    op.drop_index(op.f('ix_domain_checks_domain'), table_name='domain_checks')
    op.drop_table('domain_checks')
    # ### end Alembic commands ###
